name: Link Check

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check links
        uses: lycheeverse/lychee-action@v2.7.0
        with:
          args: --no-progress **/*.md
